apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-system-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-system
  template:
    metadata:
      labels:
        app: auth-system
    spec:
      containers:
      - name: auth-system
        image: tu-usuario-dockerhub/auth-system:latest # ¡Cambia esto por tu repo de DockerHub!
        ports:
        - containerPort: 80